# BORRAR REGISTROS #
# TENER CUIDADO POR QUE SI NO SE ESPECIFICA SE BORRARA TODO #

DELETE FROM usuarios; # CON ESTE COMANDO SE BORRA TODO #
DELETE FROM usuarios WHERE email = 'admin@admin.com';

 
